### ISSUE TITLE
Any audio ?

### ISSUE THREAD

**Issue by Entretoize** [Xyene/Emulator.NES#6]
This is very cool to have that in csharp, is it supposed to play audio ? 
Thanks

**Comment by AITYunivers** [comment]
Read the README.md, the APU isn't implemented so it doesn't support audio. Considering this seems to have been abandoned 5-6 years ago, it's more than likely that it never will have APU implemented.

**Comment by Xyene** [comment]
[This fork](https://github.com/SpyderTL/Emulator.NES) has at least some code for APU support, but I haven't tried to see if it works.

But yes, the version in this repo does not support sound.

**Comment by Entretoize** [comment]
Thank you




Le sam. 8 avr. 2023 à 18:23, Tudor Brindus ***@***.***> a
écrit :

**Comment by mediaexplorer74** [comment]
> [This fork](https://github.com/SpyderTL/Emulator.NES) has at least some code for APU support, but I haven't tried to see if it works.

I checked this  SpyderTL's fork. I used Mario game for sound micro-testing. The game "sounds" very specifically... with some audio distortions but yes, audio subsystem presents , indeed!!! Cool. Thank you very much! 

> But yes, the version in this repo does not support sound.

Xyene, tell me please, did you know Xamarin Forms "framework"? Can you help to implement SpyderTL's "audiosystem" into [Multi-platform Emulator.NES for iOS/Android/Windows](https://github.com/mediaexplorer74/XamariNES/)? 
 
 I'm retroman... and I'm very glad to recieve some lite and small "NES emulator" (not "multi-system" RetroARCH, etc.) for my old sweet Lumia windowsphone with Windows 10 Mobile :) Help me if you can...
 
Best,
MediaExplorer
